"""empty message

Revision ID: 96532421c347
Revises: 
Create Date: 2018-08-12 16:38:00.148699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96532421c347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
