"""empty message

Revision ID: b09c9c288456
Revises: 96532421c347
Create Date: 2018-08-12 16:45:50.477360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09c9c288456'
down_revision = '96532421c347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_enrolled', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_notifcations', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('text_notifcations', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'text_notifcations')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'email_notifcations')
    op.drop_column('user', 'date_enrolled')
    # ### end Alembic commands ###
